name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide detailed information to help us investigate and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched for existing issues that describe this problem
          required: true
        - label: I am using the latest version of Smart Lock Manager
          required: true
        - label: I have verified this is not a Home Assistant or Z-Wave JS issue
          required: true

  - type: input
    id: version
    attributes:
      label: Smart Lock Manager Version
      description: What version are you running? (found in HACS or manifest.json)
      placeholder: "e.g., 2025.1.0"
    validations:
      required: true

  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant are you running?
      placeholder: "e.g., 2024.8.3"
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install Smart Lock Manager?
      options:
        - HACS
        - Manual
        - Git clone
    validations:
      required: true

  - type: input
    id: lock_model
    attributes:
      label: Lock Brand/Model
      description: What lock are you using?
      placeholder: "e.g., Yale YRD256, Schlage BE469"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: |
        Please copy and paste any relevant log output from Home Assistant.
        Enable debug logging first:
        ```yaml
        logger:
          default: info
          logs:
            custom_components.smart_lock_manager: debug
        ```
      render: shell

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Your Smart Lock Manager configuration (remove sensitive data)
      render: yaml

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots

  - type: checkboxes
    id: environment
    attributes:
      label: Environment (check all that apply)
      options:
        - label: Home Assistant Core
        - label: Home Assistant Supervised
        - label: Home Assistant OS
        - label: Home Assistant Container
        - label: Running in Docker
        - label: Running on Raspberry Pi
        - label: Running on different hardware